# Exercices for Numpy

1- Import numpy as `np` and print the version number. 

In [1]:

# Your code here
import numpy as np
np.__version__


'1.23.4'

2- Create a 1D array of numbers from 0 to 9 
- Desired output:
```Python
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [5]:
ar=np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3- Create a 3×3 numpy array of all True’s
- Desired output:
```Python
#> array([[ True,  True,  True],
#>        [ True,  True,  True],
#>        [ True,  True,  True]], dtype=bool)
```

In [9]:
m=np.full((3,3),True)
m

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4- Extract all odd numbers from `arr` 
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#> array([1, 3, 5, 7, 9])
```

In [10]:
# Your code here
def extOddNum(a):
  #let's creat a list first
  arr=[]
  for i in range(len(a)):
    if a[i]%2 != 0:
      #let's test first if it's an odd number
      arr.append(a[i])
  print(arr)
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
extOddNum(arr)

[1, 3, 5, 7, 9]


5- Replace all odd numbers in arr with -1
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [14]:
def repOddNum(a):
    arr=[]
    for i in range(len(a)):
        if a[i]%2 != 0:
            a[i]=-1
    return a

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
repOddNum(arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6- Replace all odd numbers in arr with -1 without changing `arr` 
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [15]:
def repOddNum1(a):
    arr=a.copy()
    for i in range(len(arr)):
        if arr[i]%2 != 0:
            arr[i]=-1
    return arr

ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(repOddNum1(ar))
print(ar)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


7- Convert a 1D array to a 2D array with 2 rows
- Input:
```Python
#> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
```

In [16]:
def oneDtotwoD(a):
  a=a.reshape(2,-1)
  print(a)
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
oneDtotwoD(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


8- Stack arrays `a` and `b` vertically 
- Input
```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [17]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9- Stack the arrays a and b horizontally.
- Input
```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```
- Desired output:
```Python
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [18]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10- Get the common items between `a` and `b` 
- Input
```Python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
- Desired output:
```Python
#> array([2, 4])
```

In [21]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.array(set(a).intersection(set(b))))


{5}


11- From array `a` remove all items present in array `b` 
- Input
```Python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
- Desired output:
```Python
#> array([1,2,3,4])
```

In [27]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


12- Get the positions where elements of `a` and `b` match
- Input
```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```
- Desired output:
```Python
#> (array([1, 3, 5, 7]),)
```

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

13- Get all items between 5 and 10 from `a`
- Input
```Python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```
- Desired output:
```Python
#> (array([6, 9, 10]),)
```

In [37]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[np.where((a>5) & (a<11))]

array([ 6,  9, 10])

14- Convert the function `maxx` that works on two scalars, to work on two arrays
- Input
```Python
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
```
```Python
maxx(1, 5)
#> 5
```

- Desired output:

```Python
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [38]:

# Your code here
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
c=[]
for i in range(len(a)):
  m=maxx(a[i],b[i])
  c.append(m)
c

    

[6, 7, 9, 8, 9, 7, 5]

15- Reverse the rows of a 2D array `arr`
- Input
```Python
arr = np.arange(9).reshape(3,3)
```
- Desired output:
```Python
#> array([[6, 7, 8],
#>       [3, 4, 5],
#>       [0, 1, 2]])
```

In [40]:
arr = np.arange(9).reshape(3,3)
print(arr,'\n\n\n')
print(arr[::-1])



[[0 1 2]
 [3 4 5]
 [6 7 8]] 



[[6 7 8]
 [3 4 5]
 [0 1 2]]


16- Reverse the columns of a 2D array `arr`
- Input
```Python
arr = np.arange(9).reshape(3,3)
```
- Desired output:
```Python
#> array([[6, 7, 8],
#>       [3, 4, 5],
#>       [0, 1, 2]]
```

In [42]:

# Your code here
arr = np.arange(9).reshape(3,3)
print(arr,'\n\n\n')
print(np.fliplr(arr))


[[0 1 2]
 [3 4 5]
 [6 7 8]] 



[[2 1 0]
 [5 4 3]
 [8 7 6]]


17- Create a 2D array of shape 5×3 to contain random decimal numbers between 5 and 10 (use `np.random.seed()` to generate the same random output).
- Desired output: (for seed number equal 10)
```Python
#> array([[6.15037787, 9.68381843, 5.81660184],
#>       [6.33607158, 8.89081653, 9.19812181],
#>       [6.03061665, 5.87761494, 6.72743551],
#>       [7.54088093, 5.13145815, 6.41366737],
#>       [5.77872881, 7.58390137, 5.18263144]])
```

In [43]:

np.random.seed(10)
np.random.randint(low=5,high=10,size=(5,3))+np.random.random((5,3))


array([[6.15037787, 9.68381843, 5.81660184],
       [6.33607158, 8.89081653, 9.19812181],
       [6.03061665, 5.87761494, 6.72743551],
       [7.54088093, 5.13145815, 6.41366737],
       [5.77872881, 7.58390137, 5.18263144]])

18- Print or show only 3 decimal places of the numpy array `rand_arr`
- Input
```Python
rand_arr = np.random.random((5,3))
```
- Desired output:
```Python
rand_arr[:4]
#> array([[ 0.443,  0.109,  0.97 ],
#>        [ 0.388,  0.447,  0.191],
#>        [ 0.891,  0.474,  0.212],
#>        [ 0.609,  0.518,  0.403]])
```

In [44]:

# Your code here
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
print(rand_arr[:4])

[[0.826 0.105 0.284]
 [0.066 0.056 0.765]
 [0.012 0.612 0.332]
 [0.56  0.335 0.411]]


19- Pretty print `rand_arr` by suppressing the scientific notation (like 1e10) 
- Input

```Python
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
```
```Python
rand_arr

#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])
```

- Desired output:
```python
#> array([[ 0.000543,  0.000278,  0.000425],
#>        [ 0.000845,  0.000005,  0.000122],
#>        [ 0.000671,  0.000826,  0.000137]])
```

In [45]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
np.set_printoptions(suppress=True,precision=6)
print(rand_arr)

[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]
[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


20- Limit the number of items printed in python numpy array a to a maximum of 6 elements.
- Input:
```Python
a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```
- Desired output:
```Python
#> array([ 0,  1,  2, ..., 12, 13, 14])
```

In [46]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

21- Convert the 1D iris to 2D array iris_2d by omitting the species text field.
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```
- Desired output:
```Python
#> array([[ 5.1,  3.5,  1.4,  0.2],
#>        [ 4.9,  3. ,  1.4,  0.2],
#>        [ 4.7,  3.2,  1.3,  0.2],
#>        [ 4.6,  3.1,  1.5,  0.2]])
```

In [47]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d]) 
iris_2d

/tmp/ipykernel_942/586004271.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

22- Find the mean, median, standard deviation of iris's sepallength (1st column)
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
print(mean, median, sd)
#> 5.84333333333 5.8 0.825301291785
```

In [48]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
mn=np.mean(iris)
mdn=np.median(iris)
sd=np.std(iris)
print(mn," ",mdn," ",sd)

5.843333333333334   5.8   0.8253012917851409


23- Create a normalized form of iris‘s sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
print(S)
#> [ 0.222  0.167  0.111  0.083  0.194  0.306  0.083  0.194  0.028  0.167
#>   0.306  0.139  0.139  0.     0.417  0.389  0.306  0.222  0.389  0.222
#>   0.306  0.222  0.083  0.222  0.139  0.194  0.194  0.25   0.25   0.111
#>   0.139  0.306  0.25   0.333  0.167  0.194  0.333  0.167  0.028  0.222
#>   0.194  0.056  0.028  0.194  0.222  0.139  0.222  0.083  0.278  0.194
#>   0.75   0.583  0.722  0.333  0.611  0.389  0.556  0.167  0.639  0.25
#>   0.194  0.444  0.472  0.5    0.361  0.667  0.361  0.417  0.528  0.361
#>   0.444  0.5    0.556  0.5    0.583  0.639  0.694  0.667  0.472  0.389
#>   0.333  0.333  0.417  0.472  0.306  0.472  0.667  0.556  0.361  0.333
#>   0.333  0.5    0.417  0.194  0.361  0.389  0.389  0.528  0.222  0.389
#>   0.556  0.417  0.778  0.556  0.611  0.917  0.167  0.833  0.667  0.806
#>   0.611  0.583  0.694  0.389  0.417  0.583  0.611  0.944  0.944  0.472
#>   0.722  0.361  0.944  0.556  0.667  0.806  0.528  0.5    0.583  0.806
#>   0.861  1.     0.583  0.556  0.5    0.944  0.556  0.583  0.472  0.722
#>   0.667  0.722  0.417  0.694  0.667  0.667  0.556  0.611  0.528  0.444]
```

In [49]:
np.set_printoptions(precision=3)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float',usecols=[0])
imax,imin=iris.max(),iris.min()
iris=(iris-imin)/(imax-imin)

iris

array([0.222, 0.167, 0.111, ..., 0.611, 0.528, 0.444])

24- Find the number and position of missing values in iris_2d‘s sepallength (1st column)
- Input:
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```
- Desired output:
```Python
#> Number of missing values: 
...
#> Position of missing values: 
...
```

In [53]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan 
print(np.isnan(iris_2d[:,0]).sum()) 
print(np.where(np.isnan(iris_2d[:,0])))

5
(array([ 8, 44, 57, 73, 92]),)


25- Select the rows of iris_2d that does not have any nan value
- Input:
```Python
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [51]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
np.where(np.invert(np.isnan(iris_2d[0,:]))) 


(array([0, 1, 2]),)

26- Replace all ccurrences of `nan` with 0 in numpy array
- Input
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
```

In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.where(np.isnan(iris_2d))]=0
iris_2d[np.where(iris_2d==0)]

array([0., 0., 0., ..., 0., 0., 0.])

27- Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> 'small'
- 3-5 –> 'medium'
- '>=5 –> 'large'
- Input 
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
```
- Desired output:
```Python
petal_length_cat[:4]
#> ['small', 'small', 'small', 'small']
```

In [57]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]


petal_length_cat[:4]


['small', 'small', 'small', 'small']

28- Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
- Input 
```Python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
```
- Desired output:
```Python
#> 50
```

In [66]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float')
np.where(iris[:,3]>1.0)[0][0]


50

29- From the array a, replace all values greater than 30 to 30 and less than 10 to 10. 
- Input:
```Python
np.random.seed(100)
a = np.random.uniform(1,50, 20)
```
- Desired output:
```Python
#> [ 27.63  14.64  21.8   30.    10.    10.    30.    30.    10.    29.18  30.
#>   11.25  10.08  10.    11.77  30.    30.    10.    30.    14.43]
```

In [67]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a[np.where(a>30)],a[np.where(a<10)]=30,10 # locate index where the conditions are true then replace them
a


array([27.627, 14.64 , 21.801, ..., 10.   , 30.   , 14.43 ])

30- Import the image from the following URL and convert it to a numpy array. URL = ‘https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg’
- Input
```Python
from io import BytesIO
from PIL import Image
import PIL, requests
```

In [68]:
from io import BytesIO
from PIL import Image
import PIL, requests
PIL.__version__
url="https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg"
response=requests.get(url)
img = Image.open(BytesIO(response.content))
data=np.asarray(img)
print(data.shape)
data


(303, 452, 3)


array([[[  9,  72, 125],
        [  9,  72, 125],
        [  9,  72, 125],
        ...,
        [ 42, 103, 147],
        [ 42, 103, 147],
        [ 43, 104, 148]],

       [[  9,  72, 125],
        [  9,  72, 125],
        [ 10,  73, 126],
        ...,
        [ 42, 103, 147],
        [ 42, 103, 147],
        [ 43, 104, 148]],

       [[  9,  72, 125],
        [ 10,  73, 126],
        [ 10,  73, 126],
        ...,
        [ 44, 105, 150],
        [ 45, 106, 151],
        [ 45, 106, 151]],

       ...,

       [[ 21,  41,  50],
        [ 29,  51,  64],
        [ 28,  54,  69],
        ...,
        [ 27,  58,  79],
        [ 22,  53,  74],
        [ 19,  47,  69]],

       [[ 27,  51,  63],
        [ 29,  55,  68],
        [ 27,  56,  72],
        ...,
        [ 33,  70,  97],
        [ 27,  64,  91],
        [ 22,  57,  85]],

       [[ 18,  45,  56],
        [ 20,  48,  62],
        [ 21,  52,  70],
        ...,
        [ 15,  51,  77],
        [ 12,  48,  74],
        [ 11,  45,  72]]

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=1a787f8c-5294-4883-b8b0-f9da1a6d82f0' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>